[package]
name = "rrate-limiter"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["full"] }
serde = "1.0.219"
regextrie = "0.1.0"
tracing-subscriber = "0.3.17"
redis = "0.32.4"
rapidhash = "3.0.0"


[dev-dependencies]
axum-macros = "0.5.0"
