- route: "/"
  limit: 1
  expiration: 1
  algorithm: "fw"
  tracking_type: "ip"
  custom_tracking_key: ""

- route: "/api/v1/orders"
  limit: 1
  expiration: 1
  algorithm: "swc"
  tracking_type: "header"
  custom_tracking_key: "api-key"
  active : true

- route: "/api/v1/commands"
  limit: 1
  expiration: 1
  algorithm: "swl"
  tracking_type: "ip"
  custom_tracking_key: ""
