[package]
name = "config-loader"
version = "0.1.0"
edition = "2024"

[dependencies]
rrl_core ={ path = "../rrl_core"}
anyhow = "1.0.98"
serde_yaml = "0.9.34"
serde = {version="1.0.225", features = ["derive"]}
