{
 "title": "Rate Limiter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "algorithm",
    "query": {
     "query": "label_values(rl_handled_requests_total,algorithm)"
    }
   },
   {
    "name": "route",
    "label": "route",
    "query": {
     "query": "label_values(rl_handled_requests_total,name)"
    }
   },
   { "name": "tracking_type", "label": "tracking type", "query": "ip, header" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(service_name) (rl_handled_requests_total{algorithm=~\"$algorithm\", name=~\"$route\", tracking_type=~\"$tracking_type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allowed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(service_name) (rl_allowed_requests_total{algorithm=~\"$algorithm\", name=~\"$route\", tracking_type=~\"$tracking_type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(service_name) (rl_rejected_requests_total{algorithm=~\"$algorithm\", name=~\"$route\", tracking_type=~\"$tracking_type\"}) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}